name: Kubernetes CI/CD

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      chart:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PW:
        required: true
      CD_GITHUB_TOKEN:
        required: true
jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.docker_meta.outputs.tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker meta
      id: docker_meta
      run: echo "tag=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PW }}
    - name: Docker build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.repo }}:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.repo }}:${{ steps.docker_meta.outputs.tag }}
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: Jo-Jee/charts
        ref: dev
        token: ${{ secrets.CD_GITHUB_TOKEN }}
    - name: Update tag
      id: update_tag
      run: |
        version=$(cat ${{ inputs.chart }}/values.dev.yaml | grep tag: | awk '{print $2}')
        sed -i "s/$version/${{ needs.ci.outputs.tag }}/" ${{ inputs.chart }}/values.dev.yaml
        git config user.name "GitHub Action Bot"
        git config user.email "<>"
        git add .
        git push
    - name: Push chart
      run: |
        git config user.name "GitHub Action Bot"
        git config user.email "<>"
        git add .
        git commit -m "cd: ${{ inputs.repo }} tag update to ${{ needs.ci.outputs.tag }}"
        git push
